spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/irene-prod?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimeZone=UTC
    username: root
    password: 19991222xyl?
    driver-class-name: com.mysql.cj.jdbc.Driver
